### ISSUE TITLE
Shrink the image size - Duplicating #2

### ISSUE THREAD

**Issue by protenhan** [jaschac/docker-cntlm#1]
duplicate of PR #2

**Comment by jaschac** [comment]
Hello,

[ot] sorry for being super late, life had other priorities lately.[/ot]

I think your idea is indeed very good. I don't personally know Alpine very much, which is the reason I did not consider it in the very first place. I will definitely check it and your suggestion.

**Comment by protenhan** [comment]
Hi, 

thanks for getting back on this. In the meantime I forked your repo and adapted it to alpine linux. Works fine for me since a couple of months.

Thank you anyway for all the initial work in packing cntlm into a container. 👍
 https://github.com/protenhan/docker-cntlm
